name: UpdateConfig

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'

jobs:
  download_files:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create Source directory (if not exists)
        run: mkdir -p Source
  
      - name: Download files
        run: |
          curl -H "User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36" -o ./Source/Live.txt https://gitee.com/Qmyr/Qmyr/raw/master/Source/Live.txt
          curl -H "User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36" -o ./Source/Config.json https://gitee.com/Qmyr/Qmyr/raw/master/Source/Config.json
          curl -H "User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36" -o ./Source/Switch.json https://gitee.com/Qmyr/Qmyr/raw/master/Source/Switch.json
          curl -H "User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36" -o ./Source/TestConfig.json https://gitee.com/Qmyr/Qmyr/raw/master/Source/TestConfig.json
          curl -H "User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36" -o ./Source/TestSwitch.json https://gitee.com/Qmyr/Qmyr/raw/master/Source/TestSwitch.json
          curl -H "User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36" -o ./Source/CustomSpider.bmp https://gitee.com/Qmyr/Qmyr/raw/master/Source/CustomSpider.bmp

      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          message: 'Update multiple files'
          add: './Source/'
