name: Download Config.json  
on:  
  workflow_dispatch:  
  schedule:  
    - cron: '0 12 * * *'  
jobs:  
  download_config:  
    runs-on: windows-latest  
    steps:  
      - name: Checkout repository  
        uses: actions/checkout@v2  
  
      - name: Download Config.json  
        run: |  
          curl -H "User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36" -o ./Config.json https://gitee.com/Qmyr/Qmyr/raw/master/Source/Config.json  
   
      - name: Commit Config.json  
        uses: EndBug/add-and-commit@v7  
        with:  
          default_author: github_actions  
          message: 'Update Config.json'  
          add: 'Config.json'
